### ISSUE TITLE
Évaluation TP3

### ISSUE THREAD

**Issue by GabLeRoux** [raixonomas/uqac_8pro135_tp3#1]
Petite faute de frappe ici: https://github.com/raixonomas/uqac_8pro135_tp3/blob/main/README.md?plain=1#L19 Calculatrice :)

N'hésitez pas à retirer [les commentaires par défaut](https://github.com/raixonomas/uqac_8pro135_tp3/blob/main/Assets/UTF-PlayTests/UTFPlayTest_LoadMenuFromVictory.cs#L23-L24) qui sont parfois redondants.

Pour information, les fichiers de scène tels que [InitTestScene638330532928875842.unity](https://github.com/raixonomas/uqac_8pro135_tp3/blob/main/Assets/InitTestScene638330532928875842.unity) sont en fait générés lors de l'exécution des tests. On ne devrait pas les ajouter à git. C'est un petit détail, mais c'est bon à savoir.

[La release](https://github.com/raixonomas/uqac_8pro135_tp3/releases) ne semble pas avoir de description, on peut en générer une avec le bouton "Generate release notes".

Tout est là, très bon travail!

"Pour la partie bonus, on pouvait créer une release de cette manière:

```yaml
name: Create Release

on:
  push:
    tags:
      - 'v*'

# ...
      
jobs:
   buildWindows:
      # ...

  release:
    name: Create and Publish Release
    needs: prepareArtifact
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: build-StandaloneWindows64
          path: build/StandaloneWindows64

      - name: Publish Release and Upload Artifact
        uses: softprops/action-gh-release@v1
        with:
          files: build/StandaloneWindows64/build-StandaloneWindows64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

Plus de détails ici: https://github.com/softprops/action-gh-release

**Note : 100%**
